### ISSUE TITLE
Translate chrome disctipton to english

### ISSUE THREAD

**Issue by shyazusa** [shyazusa/read-late-to-GitHub-for-chrome#16]
頑張る。
現在の説明文はコチラ。

> GitHubの、指定のuser/repoのissueに、今観ているページを追加します。 あとで読む機能をGitHubで使うときにどうぞ。

↓

> Add the page you are looking at to the problem of GitHub specified user / repository. Please read when you use the function to read later on GitHub.

from GoogleTranslate.

> when you click 'New issue' button in this extensions, create new read to late issue for your target repository.

from This GitHub page discription.

Which is better?

**Comment by shyazusa** [comment]
とりあえず下のにしておく……かな。

**Comment by shyazusa** [comment]
[read-late-to-GitHub - Chrome ウェブストア](https://chrome.google.com/webstore/detail/read-late-to-github/ikenklicgfopbopbndapggfmhkjmifoi)

**Comment by lodlock** [comment]
How about:

Read Late allows you to quickly and easily capture the URL of the page you are viewing and uses it to create a new GitHub issue to your public or private repository. The issue created by Read Late is automatically assigned to you and contains the site's title and link.

Never again will you need to go through the annoying process of logging in to GitHub, selecting your repository, creating a new issue, switching to the previous page, and copying the URL. Read Late provides the same features with only a few clicks.

**Comment by shyazusa** [comment]
@lodlock I love you!!

**Comment by lodlock** [comment]
Happy to help
